### ISSUE TITLE
You are awesome, so is this project

### ISSUE THREAD

**Issue by zoontek** [klaasnotfound/LocationAssistant#1]
Hi 😄 

This is not an issue. I'm just here to say that LocationAssistant is awesome, and helped me A LOT. Location on Android is a serious mess (I had no idea), and I struggled a whole week before finding your repo.

Thanks for taking time to wrote this masterpiece 🎉

**Comment by klaasnotfound** [comment]
Hey @zoontek, 
Thanks! Glad it helped you, that's why I published it 😉 .

To get around opening an issue you're also welcome to leave a comment on [the corresponding blog post](http://www.klaasnotfound.com/2016/05/27/location-on-android-stop-mocking-me/), if you like.

Closing this (non-)issue, then... 😛
