### ISSUE TITLE
mock locations from "Fake GPS JoyStick" app are not being rejected

### ISSUE THREAD

**Issue by napcosta** [klaasnotfound/LocationAssistant#3]
My device is an LG G3 with Android 5.0

Were you aware of this issue?

Thank you for your work!

**Comment by klaasnotfound** [comment]
Hi @shadowpt, thanks for pointing this out. I installed the app and can confirm the locations manage to sneak by the mock detection. This seems to be due to an exploit that allowed apps even on non-rooted devices to hide the mock flag:
https://pokemongohub.net/android-7-1-security-update-disables-gps-spoofing-pokemon-go/

As part of an Android security patch this exploit has been fixed in Android 7.1. and according to the article might be fixed in updates for older Android versions. 
https://android.googlesource.com/platform/frameworks/base/+/d22261fef84481651e12995062105239d551cbc6

I am not sure how many "old" devices these updates will effectively roll out to, but the problem will (slowly) heal over time...

The `LocationAssistant` relies on the mock flag being set at least for _some_ locations, so there is not much we can do for devices that are either rooted or make use of the exploit. In theory, one could implement a more advanced logic to detect fake locations (compare locations from the WiFi / non-GPS providers against possibly fake GPS location readings), but this would mean building a full-blown location fusion logic from scratch and would go way beyond what I intended the LocationAssistant to do.

I'm closing this issue for now. If you have suggestions for a possible fix or want to investigate deeper, feel free to comment / reopen it.
