### ISSUE TITLE
Always getting Speed and Bearing values as zero

### ISSUE THREAD

**Issue by Shhzdmrz** [klaasnotfound/LocationAssistant#4]
Hi,

I am able to get the latitude and longitude but speed and direction always zero. I don't know what is the issue. the issue can be because of the device? or its the required behavior from this repo.

Thanks

**Comment by klaasnotfound** [comment]
Hi @Shhzdmrz ,

this doesn't sound like it's due to the `LocationAssistant`. Even in the [log output](https://www.klaasnotfound.com/assets/content/stop_mocking_me_06.png) from my original [blog post](https://www.klaasnotfound.com/2016/05/27/location-on-android-stop-mocking-me/) (where the device was stationary on a desk) the velocity had non-zero values.

It's probably either due to the device or because the `FusedLocationProvider` is not using the GPS sensor as a source for some reason. You could check the former by building a simple app that uses the `LocationManager` with GPS directly. If you're getting GPS readings with velocity and bearing, your device is fine; if not, something is amiss. When using the fused provider via the `LocationAssistant` be sure to instantiate it with `LocationAssistant.Accuracy.HIGH`, otherwise GPS might not be used.

Finally, from my understanding of the fused location API, in certain scenarios (e.g. an urban canyon with lots of WiFi, but no GPS signal) GPS might not be used as a source, _even if the accuracy is set to_ `HIGH`. In this case, you would also not get bearing and/or velocity in the fused locations. You can read [a bit more on that here](https://stackoverflow.com/a/40173368/6424399).

Closing this issue. Feel free to comment or re-open if you believe there is an issue with the `LocationAssistant`.
